language: node_js
node_js:
  - '4.5.0'
cache:
  directories:
    - node_modules
before_install:
  - npm install
  - npm install -g hexo-cli
script:
  - hexo generate
after_script:
  - Capybara.default_wait_time = 15
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: publish
  on:
    branch: master
