language: node_js
node_js:
  - '6.9.0'
cache: node_modules
script:
  - ./node_modules/hexo/bin/hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  email: ldllidonglin@sina.com
  name: ldllidonglin
  on:
    branch: master
