language: node_js
node_js:
  - '4.5.0'
cache: node_modules
before_install:
  - npm install -g hexo-cli
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  email: ldllidonglin@sina.com
  name: ldllidonglin
  on:
    branch: master
